language: ruby

cache: bundler

rvm:
  - 2.0.0
  - 2.1
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head

gemfile:
  - test/gemfiles/1.0
  - test/gemfiles/1.1
  - test/gemfiles/1.2
  - test/gemfiles/1.3
  - test/gemfiles/1.4
  - test/gemfiles/1.5
  - test/gemfiles/1.6
  - test/gemfiles/1.7
  - test/gemfiles/1.8
  - test/gemfiles/1.9
  - test/gemfiles/1.10

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
